name: Cypress UI Tests + Allure Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 16 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx cypress verify

      - run: |
          mkdir -p allure-results
          npx cypress run --browser chrome --headless
        continue-on-error: true

      - run: npm install -g allure-commandline

      - run: |
          rm -rf allure-report
          allure generate allure-results --clean -o allure-report

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: true